title: 'London BitDevs'
tagline: 'London BitDevs is a community of Bitcoin enthusiasts and professionals interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Events', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/BitDevsLDN/', external: true}
